# Generated by Django 4.0.4 on 2022-06-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='Imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
